fix: Update helm upgrade command (#39)
Missing release name for `helm upgrade --install` command. Without it,
it throws an error.

```
$ helm upgrade --install nr-operator/newrelic-k8s-operator -f values.yaml -n newrelic
Error: "helm upgrade" requires 2 arguments

Usage:  helm upgrade [RELEASE] [CHART] [flags]
```